#---------------------------------------------------------------------------
#
# 	File: Makefile.sample 
#	
#		For ubuntu v16 12/23/17
#
#---------------------------------------------------------------------------

#  change these to point to the build direcorties for the program &misc X source
#
Home = /home/lxb
XDIR = /home/lxb/lxb/oldX11
PGM = editres

CC=gcc
CDEBUGFLAGS = -g -ggdb

DEFINES =
# INCLUDES = -I../include -I$(XDIR)/include -I/usr/include/x86_64-linux-gnu -I/usr/lib/gcc/x86_64-linux-gnu/5/include

INCLUDES = -I../include -I$(XDIR)/include 


CFLAGS = $(CDEBUGFLAGS) $(INCLUDES) $(DEFINES)
LDFLAGS = -o

#
#  use my built and installed Motif library - Ubuntu v16 12/23/17
#
#    -the libs exist but not the header files for all X11
#    - built and installed the latest Motif libs from Sourceforge
#    - need to have libs in this order or get a bad window error
#
XLIBS = -lXm -lX11 -lXmu -lXt -lXaw

LIBS = $(XLIBS)

#---------------------------------------------------------------------------
OBJS = actions.o \
comm.o \
editres.o \
geometry.o \
handler.o \
setvalues.o \
svpopup.o \
utils.o \
widgets.o \
wtree.o 

#---------------------------------------------------------------------------

$(PGM): $(OBJS) 
	$(CC) $(LDFLAGS) $(PGM) $(OBJS) $(LIBS) 

relink:
	rm -f $(PGM)
	$(CC) $(LDFLAGS) $(PGM) $(OBJS) $(LIBS)

#all: clean depend $(PGM)
all: clean $(PGM) ctags

clean:
	rm -f $(PGM) *.o *.a 

ctags:	
	ctags -S *.c

depend:	
	makedepend $(INCLUDES) $(DEFINES) *.c


# DO NOT DELETE

actions.o: /usr/include/stdio.h /usr/include/features.h
actions.o: /usr/include/stdc-predef.h
actions.o: /usr/include/x86_64-linux-gnu/sys/cdefs.h
actions.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
actions.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
actions.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
actions.o: /usr/include/x86_64-linux-gnu/bits/types.h
actions.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h
actions.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
actions.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
actions.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
actions.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
actions.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
actions.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/time.h
actions.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
actions.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
actions.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
actions.o: /usr/include/x86_64-linux-gnu/sys/select.h
actions.o: /usr/include/x86_64-linux-gnu/bits/select.h
actions.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
actions.o: /usr/include/x86_64-linux-gnu/bits/time.h
actions.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
actions.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
actions.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
actions.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
actions.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
actions.o: /usr/include/X11/Xresource.h /usr/include/string.h
actions.o: /usr/include/xlocale.h /usr/include/X11/Core.h
actions.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
actions.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
actions.o: /home/lxb/lxb/oldX11/include/X11/Xmu/CharSet.h
actions.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h editresP.h
actions.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
comm.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
comm.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/features.h
comm.o: /usr/include/stdc-predef.h /usr/include/x86_64-linux-gnu/sys/cdefs.h
comm.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
comm.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
comm.o: /usr/include/x86_64-linux-gnu/bits/types.h
comm.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h /usr/include/time.h
comm.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
comm.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
comm.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
comm.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
comm.o: /usr/include/x86_64-linux-gnu/sys/select.h
comm.o: /usr/include/x86_64-linux-gnu/bits/select.h
comm.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
comm.o: /usr/include/x86_64-linux-gnu/bits/time.h
comm.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
comm.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
comm.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
comm.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
comm.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
comm.o: /usr/include/X11/Xresource.h /usr/include/string.h
comm.o: /usr/include/xlocale.h /usr/include/X11/Core.h
comm.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
comm.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
comm.o: /usr/include/X11/StringDefs.h /usr/include/X11/Xatom.h
comm.o: /usr/include/X11/cursorfont.h /usr/include/X11/Xproto.h
comm.o: /usr/include/X11/Xmd.h /usr/include/X11/Xprotostr.h
comm.o: /usr/include/X11/Xos.h /usr/include/fcntl.h
comm.o: /usr/include/x86_64-linux-gnu/bits/fcntl.h
comm.o: /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h
comm.o: /usr/include/x86_64-linux-gnu/bits/stat.h /usr/include/unistd.h
comm.o: /usr/include/x86_64-linux-gnu/bits/posix_opt.h
comm.o: /usr/include/x86_64-linux-gnu/bits/environments.h
comm.o: /usr/include/x86_64-linux-gnu/bits/confname.h /usr/include/getopt.h
comm.o: /usr/include/x86_64-linux-gnu/sys/time.h /usr/include/X11/Xarch.h
comm.o: /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h
comm.o: /usr/include/wchar.h /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
comm.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
comm.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
comm.o: /home/lxb/lxb/oldX11/include/X11/Xmu/Error.h editresP.h
comm.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
editres.o: /usr/include/stdio.h /usr/include/features.h
editres.o: /usr/include/stdc-predef.h
editres.o: /usr/include/x86_64-linux-gnu/sys/cdefs.h
editres.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
editres.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
editres.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
editres.o: /usr/include/x86_64-linux-gnu/bits/types.h
editres.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h
editres.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
editres.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
editres.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
editres.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
editres.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
editres.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/time.h
editres.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
editres.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
editres.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
editres.o: /usr/include/x86_64-linux-gnu/sys/select.h
editres.o: /usr/include/x86_64-linux-gnu/bits/select.h
editres.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
editres.o: /usr/include/x86_64-linux-gnu/bits/time.h
editres.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
editres.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
editres.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
editres.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
editres.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
editres.o: /usr/include/X11/Xresource.h /usr/include/string.h
editres.o: /usr/include/xlocale.h /usr/include/X11/Core.h
editres.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
editres.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
editres.o: /usr/include/X11/StringDefs.h
editres.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h editresP.h
editres.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
geometry.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
geometry.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/features.h
geometry.o: /usr/include/stdc-predef.h
geometry.o: /usr/include/x86_64-linux-gnu/sys/cdefs.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
geometry.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/types.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h
geometry.o: /usr/include/time.h
geometry.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
geometry.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
geometry.o: /usr/include/x86_64-linux-gnu/sys/select.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/select.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/time.h
geometry.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
geometry.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
geometry.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
geometry.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
geometry.o: /usr/include/X11/Xresource.h /usr/include/string.h
geometry.o: /usr/include/xlocale.h /usr/include/X11/Core.h
geometry.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
geometry.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
geometry.o: /usr/include/X11/StringDefs.h /usr/include/X11/Shell.h
geometry.o: /usr/include/X11/SM/SMlib.h /usr/include/X11/SM/SM.h
geometry.o: /usr/include/X11/ICE/ICElib.h /usr/include/X11/ICE/ICE.h
geometry.o: /usr/include/stdio.h /usr/include/libio.h
geometry.o: /usr/include/_G_config.h /usr/include/wchar.h
geometry.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
geometry.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
geometry.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h editresP.h
geometry.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
handler.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
handler.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/features.h
handler.o: /usr/include/stdc-predef.h
handler.o: /usr/include/x86_64-linux-gnu/sys/cdefs.h
handler.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
handler.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
handler.o: /usr/include/x86_64-linux-gnu/bits/types.h
handler.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h /usr/include/time.h
handler.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
handler.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
handler.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
handler.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
handler.o: /usr/include/x86_64-linux-gnu/sys/select.h
handler.o: /usr/include/x86_64-linux-gnu/bits/select.h
handler.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
handler.o: /usr/include/x86_64-linux-gnu/bits/time.h
handler.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
handler.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
handler.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
handler.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
handler.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
handler.o: /usr/include/X11/Xresource.h /usr/include/string.h
handler.o: /usr/include/xlocale.h /usr/include/X11/Core.h
handler.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
handler.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
handler.o: /usr/include/X11/StringDefs.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/List.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Simple.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xmu/Converters.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Panner.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Reports.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Toggle.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Command.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Label.h
handler.o: /usr/include/X11/Xfuncs.h /usr/include/X11/Xos.h
handler.o: /usr/include/fcntl.h /usr/include/x86_64-linux-gnu/bits/fcntl.h
handler.o: /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h
handler.o: /usr/include/x86_64-linux-gnu/bits/stat.h /usr/include/unistd.h
handler.o: /usr/include/x86_64-linux-gnu/bits/posix_opt.h
handler.o: /usr/include/x86_64-linux-gnu/bits/environments.h
handler.o: /usr/include/x86_64-linux-gnu/bits/confname.h
handler.o: /usr/include/getopt.h /usr/include/x86_64-linux-gnu/sys/time.h
handler.o: /usr/include/X11/Xarch.h /usr/include/stdio.h /usr/include/libio.h
handler.o: /usr/include/_G_config.h /usr/include/wchar.h
handler.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
handler.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
handler.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h editresP.h
handler.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
setvalues.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
setvalues.o: /usr/include/x86_64-linux-gnu/sys/types.h
setvalues.o: /usr/include/features.h /usr/include/stdc-predef.h
setvalues.o: /usr/include/x86_64-linux-gnu/sys/cdefs.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
setvalues.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/types.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h
setvalues.o: /usr/include/time.h
setvalues.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
setvalues.o: /usr/include/endian.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/endian.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
setvalues.o: /usr/include/x86_64-linux-gnu/sys/select.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/select.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/time.h
setvalues.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
setvalues.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
setvalues.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
setvalues.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
setvalues.o: /usr/include/X11/Xresource.h /usr/include/string.h
setvalues.o: /usr/include/xlocale.h /usr/include/X11/Core.h
setvalues.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
setvalues.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
setvalues.o: /usr/include/X11/StringDefs.h /usr/include/stdio.h
setvalues.o: /usr/include/libio.h /usr/include/_G_config.h
setvalues.o: /usr/include/wchar.h
setvalues.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiText.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Text.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Simple.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xmu/Converters.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/TextSink.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/TextSrc.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiSrc.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiSink.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/MultiSrc.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h
setvalues.o: /usr/include/X11/Xfuncs.h /usr/include/X11/Xos.h
setvalues.o: /usr/include/fcntl.h /usr/include/x86_64-linux-gnu/bits/fcntl.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/stat.h /usr/include/unistd.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/posix_opt.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/environments.h
setvalues.o: /usr/include/x86_64-linux-gnu/bits/confname.h
setvalues.o: /usr/include/getopt.h /usr/include/x86_64-linux-gnu/sys/time.h
setvalues.o: /usr/include/X11/Xarch.h editresP.h
setvalues.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
svpopup.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
svpopup.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/features.h
svpopup.o: /usr/include/stdc-predef.h
svpopup.o: /usr/include/x86_64-linux-gnu/sys/cdefs.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
svpopup.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/types.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h /usr/include/time.h
svpopup.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
svpopup.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
svpopup.o: /usr/include/x86_64-linux-gnu/sys/select.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/select.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/time.h
svpopup.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
svpopup.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
svpopup.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
svpopup.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
svpopup.o: /usr/include/X11/Xresource.h /usr/include/string.h
svpopup.o: /usr/include/xlocale.h /usr/include/X11/Core.h
svpopup.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
svpopup.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
svpopup.o: /usr/include/X11/StringDefs.h /usr/include/X11/Xatom.h
svpopup.o: /usr/include/X11/cursorfont.h /usr/include/X11/Shell.h
svpopup.o: /usr/include/X11/SM/SMlib.h /usr/include/X11/SM/SM.h
svpopup.o: /usr/include/X11/ICE/ICElib.h /usr/include/X11/ICE/ICE.h
svpopup.o: editresP.h /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiText.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Text.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Simple.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xmu/Converters.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/TextSink.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/TextSrc.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiSrc.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiSink.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/MultiSrc.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Command.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Label.h
svpopup.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Form.h /usr/include/stdio.h
svpopup.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
svpopup.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
svpopup.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
utils.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
utils.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/features.h
utils.o: /usr/include/stdc-predef.h /usr/include/x86_64-linux-gnu/sys/cdefs.h
utils.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
utils.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
utils.o: /usr/include/x86_64-linux-gnu/bits/types.h
utils.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h /usr/include/time.h
utils.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
utils.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
utils.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
utils.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
utils.o: /usr/include/x86_64-linux-gnu/sys/select.h
utils.o: /usr/include/x86_64-linux-gnu/bits/select.h
utils.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
utils.o: /usr/include/x86_64-linux-gnu/bits/time.h
utils.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
utils.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
utils.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
utils.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
utils.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
utils.o: /usr/include/X11/Xresource.h /usr/include/string.h
utils.o: /usr/include/xlocale.h /usr/include/X11/Core.h
utils.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
utils.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
utils.o: /usr/include/X11/Xos.h /usr/include/fcntl.h
utils.o: /usr/include/x86_64-linux-gnu/bits/fcntl.h
utils.o: /usr/include/x86_64-linux-gnu/bits/fcntl-linux.h
utils.o: /usr/include/x86_64-linux-gnu/bits/stat.h /usr/include/unistd.h
utils.o: /usr/include/x86_64-linux-gnu/bits/posix_opt.h
utils.o: /usr/include/x86_64-linux-gnu/bits/environments.h
utils.o: /usr/include/x86_64-linux-gnu/bits/confname.h /usr/include/getopt.h
utils.o: /usr/include/x86_64-linux-gnu/sys/time.h /usr/include/X11/Xarch.h
utils.o: /usr/include/X11/Shell.h /usr/include/X11/SM/SMlib.h
utils.o: /usr/include/X11/SM/SM.h /usr/include/X11/ICE/ICElib.h
utils.o: /usr/include/X11/ICE/ICE.h /usr/include/X11/StringDefs.h
utils.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h
utils.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Dialog.h
utils.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Form.h /usr/include/stdio.h
utils.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
utils.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
utils.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
utils.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h editresP.h
utils.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
widgets.o: /usr/include/stdio.h /usr/include/features.h
widgets.o: /usr/include/stdc-predef.h
widgets.o: /usr/include/x86_64-linux-gnu/sys/cdefs.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
widgets.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
widgets.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/types.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h
widgets.o: /usr/include/libio.h /usr/include/_G_config.h /usr/include/wchar.h
widgets.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
widgets.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
widgets.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/time.h
widgets.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
widgets.o: /usr/include/x86_64-linux-gnu/sys/select.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/select.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/time.h
widgets.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
widgets.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
widgets.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
widgets.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
widgets.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
widgets.o: /usr/include/X11/Xresource.h /usr/include/string.h
widgets.o: /usr/include/xlocale.h /usr/include/X11/Core.h
widgets.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
widgets.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
widgets.o: /usr/include/X11/StringDefs.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiText.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Text.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Simple.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xmu/Converters.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/TextSink.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/TextSrc.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiSrc.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/AsciiSink.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/MultiSrc.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Box.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Label.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/List.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/MenuButton.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Command.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Paned.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Panner.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Reports.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Porthole.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/SmeBSB.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Sme.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/SmeLine.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/SimpleMenu.h
widgets.o: /usr/include/X11/Shell.h /usr/include/X11/SM/SMlib.h
widgets.o: /usr/include/X11/SM/SM.h /usr/include/X11/ICE/ICElib.h
widgets.o: /usr/include/X11/ICE/ICE.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Toggle.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Tree.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Viewport.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Form.h editresP.h
widgets.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
wtree.o: /usr/include/stdio.h /usr/include/features.h
wtree.o: /usr/include/stdc-predef.h /usr/include/x86_64-linux-gnu/sys/cdefs.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/wordsize.h
wtree.o: /usr/include/x86_64-linux-gnu/gnu/stubs.h
wtree.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stddef.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/types.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/typesizes.h /usr/include/libio.h
wtree.o: /usr/include/_G_config.h /usr/include/wchar.h
wtree.o: /usr/lib/gcc/x86_64-linux-gnu/5/include/stdarg.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/stdio_lim.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/sys_errlist.h
wtree.o: /usr/include/X11/Intrinsic.h /usr/include/X11/Xlib.h
wtree.o: /usr/include/x86_64-linux-gnu/sys/types.h /usr/include/time.h
wtree.o: /usr/include/endian.h /usr/include/x86_64-linux-gnu/bits/endian.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/byteswap.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/byteswap-16.h
wtree.o: /usr/include/x86_64-linux-gnu/sys/select.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/select.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/sigset.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/time.h
wtree.o: /usr/include/x86_64-linux-gnu/sys/sysmacros.h
wtree.o: /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
wtree.o: /usr/include/X11/X.h /usr/include/X11/Xfuncproto.h
wtree.o: /usr/include/X11/Xosdefs.h /usr/include/X11/Xutil.h
wtree.o: /usr/include/X11/keysym.h /usr/include/X11/keysymdef.h
wtree.o: /usr/include/X11/Xresource.h /usr/include/string.h
wtree.o: /usr/include/xlocale.h /usr/include/X11/Core.h
wtree.o: /usr/include/X11/Composite.h /usr/include/X11/Constraint.h
wtree.o: /usr/include/X11/Object.h /usr/include/X11/RectObj.h
wtree.o: /usr/include/X11/StringDefs.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Cardinals.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Toggle.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Command.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Label.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Simple.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xmu/Converters.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Viewport.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Form.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Reports.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xaw/Tree.h editresP.h
wtree.o: /home/lxb/lxb/oldX11/include/X11/Xmu/EditresP.h
