/**************************************************
* File: menubar_app.h - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* external variables */
extern Widget menubar_app;
extern Widget form_1;
extern Widget menushell_3;
extern Widget pulldown_4;
extern Widget pulldown_6;
extern Widget pulldown_8;
extern Widget scrolledWindow_17;
extern Widget text_18;
extern Widget HorScrollBar;
extern Widget VertScrollBar;

