/**************************************************
* File: menubar_app.c - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* include files */
#include <stdio.h>

#include <Xm/Xm.h>
#include <Xm/ScrolledW.h>
#include <Xm/ScrollBar.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include <Xm/ArrowB.h>
#include <Xm/CascadeB.h>
#include <Xm/Separator.h>
#include <Xm/DrawnB.h>
#include <Xm/Scale.h>
#include <Xm/Frame.h>
#include <Xm/Form.h>
#include <Xm/RowColumn.h>
#include <Xm/Label.h>
#include <Xm/TextF.h>
#include <Xm/Text.h>
#include <Xm/List.h>
#include <Xm/DrawingA.h>
#include <Xm/MenuShell.h>
#include <X11/Shell.h>

#include "menubar_app_util.h"
#include "menubar_app.h"

/* global variables */
Widget menubar_app;
Widget form_1;
Widget menushell_3;
Widget pulldown_4;
Widget pulldown_6;
Widget pulldown_8;
Widget scrolledWindow_17;
Widget text_18;

/* local prototypes */
static void
build_gui(Widget menubar_app);

/**************************************************
* Function: build_gui
**************************************************/
static void
build_gui(Widget menubar_app)
{
	Arg args[100];
	XmString xmstrings[10];
	XmFontList fontlist;
	Widget menubar1;
	Widget Files;
	Widget Edit;
	Widget Options;
	Widget pb0;
	Widget pushButton_12;
	Widget pushButton_13;
	Widget pushButton_14;
	Widget separator_15;
	Widget pushButton_16;
	Widget toggleButton_21;
	Widget toggleButton_22;

	XtSetArg(args[0], XmNy, 597);
	XtSetArg(args[1], XmNx, 256);
	XtSetArg(args[2], XmNrubberPositioning, False);
	XtSetArg(args[3], XmNresizePolicy, XmRESIZE_NONE);
	XtSetArg(args[4], XmNheight, 60);
	XtSetArg(args[5], XmNwidth, 60);
	form_1 = XtCreateManagedWidget("form_1", xmFormWidgetClass, menubar_app, args, 6);

	XtSetArg(args[0], XmNrightAttachment, XmATTACH_FORM);
	XtSetArg(args[1], XmNbottomAttachment, XmATTACH_NONE);
	XtSetArg(args[2], XmNleftAttachment, XmATTACH_FORM);
	XtSetArg(args[3], XmNtopAttachment, XmATTACH_FORM);
	XtSetArg(args[4], XmNrowColumnType, XmMENU_BAR);
	XtSetArg(args[5], XmNheight, 30);
	XtSetArg(args[6], XmNwidth, 100);
	menubar1 = XtCreateManagedWidget("menubar1", xmRowColumnWidgetClass, form_1, args, 7);

	XtSetArg(args[0], XmNheight, 1);
	XtSetArg(args[1], XmNwidth, 1);
	menushell_3 = XmCreateMenuShell(menubar1, "menushell_3", args, 2);
	XtManageChild(menushell_3);

	XtSetArg(args[0], XmNrowColumnType, XmMENU_PULLDOWN);
	pulldown_4 = XtCreateWidget("pulldown_4", xmRowColumnWidgetClass, menushell_3, args, 1);

	xmstrings[0] = XmStringCreateSimple("Files");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	XtSetArg(args[1], XmNy, 5);
	XtSetArg(args[2], XmNx, 5);
	XtSetArg(args[3], XmNsubMenuId, pulldown_4);
	Files = XtCreateManagedWidget("Files", xmCascadeButtonWidgetClass, menubar1, args, 4);

	XmStringFree(xmstrings[0]);

	XtSetArg(args[0], XmNrowColumnType, XmMENU_PULLDOWN);
	pulldown_6 = XtCreateWidget("pulldown_6", xmRowColumnWidgetClass, menushell_3, args, 1);

	xmstrings[0] = XmStringCreateSimple("Edit");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	XtSetArg(args[1], XmNy, 5);
	XtSetArg(args[2], XmNx, 48);
	XtSetArg(args[3], XmNsubMenuId, pulldown_6);
	Edit = XtCreateManagedWidget("Edit", xmCascadeButtonWidgetClass, menubar1, args, 4);

	XmStringFree(xmstrings[0]);

	XtSetArg(args[0], XmNrowColumnType, XmMENU_PULLDOWN);
	pulldown_8 = XtCreateWidget("pulldown_8", xmRowColumnWidgetClass, menushell_3, args, 1);

	xmstrings[0] = XmStringCreateSimple("Options");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	XtSetArg(args[1], XmNy, 5);
	XtSetArg(args[2], XmNx, 87);
	XtSetArg(args[3], XmNsubMenuId, pulldown_8);
	Options = XtCreateManagedWidget("Options", xmCascadeButtonWidgetClass, menubar1, args, 4);

	XmStringFree(xmstrings[0]);

	XtSetArg(args[0], XmNy, 2);
	XtSetArg(args[1], XmNx, 2);
	xmstrings[0] = XmStringCreateSimple("New");
	XtSetArg(args[2], XmNlabelString, xmstrings[0]);
	pb0 = XtCreateManagedWidget("pb0", xmPushButtonWidgetClass, pulldown_4, args, 3);

	XmStringFree(xmstrings[0]);

	xmstrings[0] = XmStringCreateSimple("Save");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	pushButton_12 = XtCreateManagedWidget("pushButton_12", xmPushButtonWidgetClass, pulldown_4, args, 1);

	XmStringFree(xmstrings[0]);

	XtSetArg(args[0], XmNy, 48);
	XtSetArg(args[1], XmNx, 2);
	xmstrings[0] = XmStringCreateSimple("Quit");
	XtSetArg(args[2], XmNlabelString, xmstrings[0]);
	pushButton_13 = XtCreateManagedWidget("pushButton_13", xmPushButtonWidgetClass, pulldown_4, args, 3);

	XmStringFree(xmstrings[0]);

	xmstrings[0] = XmStringCreateSimple("Cut");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	pushButton_14 = XtCreateManagedWidget("pushButton_14", xmPushButtonWidgetClass, pulldown_6, args, 1);

	XmStringFree(xmstrings[0]);

	separator_15 = XtCreateManagedWidget("separator_15", xmSeparatorWidgetClass, pulldown_6, args, 0);

	xmstrings[0] = XmStringCreateSimple("Paste");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	pushButton_16 = XtCreateManagedWidget("pushButton_16", xmPushButtonWidgetClass, pulldown_6, args, 1);

	XmStringFree(xmstrings[0]);

	XtSetArg(args[0], XmNrightAttachment, XmATTACH_FORM);
	XtSetArg(args[1], XmNbottomAttachment, XmATTACH_FORM);
	XtSetArg(args[2], XmNleftAttachment, XmATTACH_FORM);
	XtSetArg(args[3], XmNtopWidget, menubar1);
	XtSetArg(args[4], XmNtopAttachment, XmATTACH_WIDGET);
	XtSetArg(args[5], XmNshadowThickness, 0);
	XtSetArg(args[6], XmNscrollBarDisplayPolicy, XmSTATIC);
	XtSetArg(args[7], XmNvisualPolicy, XmVARIABLE);
	XtSetArg(args[8], XmNscrollingPolicy, XmAPPLICATION_DEFINED);
	XtSetArg(args[9], XmNheight, 60);
	XtSetArg(args[10], XmNwidth, 60);
	XtSetArg(args[11], XmNy, 0);
	XtSetArg(args[12], XmNx, 0);
	scrolledWindow_17 = XtCreateManagedWidget("scrolledWindow_17", xmScrolledWindowWidgetClass, form_1, args, 13);

	XtSetArg(args[0], XmNforeground, get_pixel(menubar_app, "PeachPuff"));
	XtSetArg(args[1], XmNbackground, get_pixel(menubar_app, "LightSteelBlue4"));
	XtSetArg(args[2], XmNy, 0);
	XtSetArg(args[3], XmNx, 0);
	XtSetArg(args[4], XmNheight, 100);
	XtSetArg(args[5], XmNwidth, 100);
	XtSetArg(args[6], XmNeditMode, XmMULTI_LINE_EDIT);
	text_18 = XtCreateManagedWidget("text_18", xmTextWidgetClass, scrolledWindow_17, args, 7);

	xmstrings[0] = XmStringCreateSimple("Option 1");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	toggleButton_21 = XtCreateManagedWidget("toggleButton_21", xmToggleButtonWidgetClass, pulldown_8, args, 1);

	XmStringFree(xmstrings[0]);

	xmstrings[0] = XmStringCreateSimple("Option 2");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	toggleButton_22 = XtCreateManagedWidget("toggleButton_22", xmToggleButtonWidgetClass, pulldown_8, args, 1);

	XmStringFree(xmstrings[0]);

}
/**************************************************
* Function: main
**************************************************/
int 
main(int argc, char *argv[])
{
	Arg args[100];

	/* Initialize toolkit and parse command line options. */
	menubar_app = XtInitialize(NULL, "menubar_app", NULL, 0, &argc, argv);

	XtSetArg(args[0], XmNgeometry, "577x355+256+597");
	XtSetValues(menubar_app, args, 1);

	build_gui(menubar_app);

	XtRealizeWidget(menubar_app);

	XtMainLoop();
}
