/**************************************************
* File: lxbApp.c - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* include files */
#include <stdio.h>

#include <Xm/Xm.h>
#include <Xm/ScrolledW.h>
#include <Xm/ScrollBar.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include <Xm/ArrowB.h>
#include <Xm/CascadeB.h>
#include <Xm/Separator.h>
#include <Xm/DrawnB.h>
#include <Xm/Scale.h>
#include <Xm/Frame.h>
#include <Xm/Form.h>
#include <Xm/RowColumn.h>
#include <Xm/Label.h>
#include <Xm/TextF.h>
#include <Xm/Text.h>
#include <Xm/List.h>
#include <Xm/DrawingA.h>
#include <Xm/MenuShell.h>
#include <X11/Shell.h>

#include "lxbApp_util.h"
#include "lxbApp.h"

/* global variables */

Widget topLevelShell;
Widget drawingArea_2;
Widget rowColumn_3;
Widget textF_4;
Widget pushButton_5;
Widget pushButton_6;

/* local prototypes */
static void
build_gui(Widget topLevelShell);

/**************************************************
* Function: build_gui
**************************************************/
static void
build_gui(Widget topLevelShell)
{
	Arg args[100];
	XmString xmstrings[10];
	XmFontList fontlist;

	XtSetArg(args[0], XmNy, 0);
	XtSetArg(args[1], XmNx, 0);
	XtSetArg(args[2], XmNresizePolicy, XmRESIZE_NONE);
	XtSetArg(args[3], XmNheight, 60);
	XtSetArg(args[4], XmNwidth, 60);
	drawingArea_2 = XtCreateManagedWidget("drawingArea_2", xmDrawingAreaWidgetClass, topLevelShell, args, 5);

	XtSetArg(args[0], XmNorientation, XmHORIZONTAL);
	XtSetArg(args[1], XmNbackground, get_pixel(topLevelShell, "gray93"));
	XtSetArg(args[2], XmNnoResize, False);
	XtSetArg(args[3], XmNwidth, 60);
	XtSetArg(args[4], XmNheight, 10);
	rowColumn_3 = XtCreateManagedWidget("rowColumn_3", xmRowColumnWidgetClass, drawingArea_2, args, 5);

	textF_4 = XtCreateManagedWidget("textF_4", xmTextFieldWidgetClass, rowColumn_3, args, 0);

	xmstrings[0] = XmStringCreateSimple("Ok");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	XtSetArg(args[1], XmNy, 3);
	XtSetArg(args[2], XmNx, 184);
	pushButton_5 = XtCreateManagedWidget("pushButton_5", xmPushButtonWidgetClass, rowColumn_3, args, 3);

	XmStringFree(xmstrings[0]);

	xmstrings[0] = XmStringCreateSimple("Cancel");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	XtSetArg(args[1], XmNy, 3);
	XtSetArg(args[2], XmNx, 220);
	pushButton_6 = XtCreateManagedWidget("pushButton_6", xmPushButtonWidgetClass, rowColumn_3, args, 3);

	XmStringFree(xmstrings[0]);

}
/**************************************************
* Function: main
**************************************************/
int 
main(int argc, char *argv[])
{
	Arg args[100];

	/* Initialize toolkit and parse command line options. */
	topLevelShell = XtInitialize(NULL, "lxbApp", NULL, 0, &argc, argv);

	XtSetArg(args[0], XmNgeometry, "558x174+330+496");
	XtSetValues(topLevelShell, args, 1);

	build_gui(topLevelShell);

	XtRealizeWidget(topLevelShell);

	XtMainLoop();
}
