/**************************************************
* File: lxbApp.h - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* external variables */

extern Widget topLevelShell;
extern Widget drawingArea_2;
extern Widget rowColumn_3;
extern Widget textF_4;
extern Widget pushButton_5;
extern Widget pushButton_6;

