/**************************************************
* File: lxbApp.c - application source file
*
*    This file is generated by the program lxb.
*
*	Test the text objects.
*
**************************************************/

/* include files */
#include <Xm/Xm.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/DrawingA.h>
#include <Xm/TextF.h>

#include "lxbApp_util.h"
#include "text_object.h"
#include "tst.h"

/**************************************************
* Function: tst
**************************************************/
static Boolean
tst(Widget w, char *txt)
{
	printf("text was %s\n", txt);
	return (True);
}
/**************************************************
* Function: main
**************************************************/
int 
main(int argc, char *argv[])
{
	Arg args[10];
	Widget topLevelShell;
	Widget d;
	Widget t;
	Widget t1;
	Widget rc;

	/* Initialize toolkit and parse command line options. */
	topLevelShell = XtInitialize(NULL, "lxbApp", NULL, 0, &argc, argv);

	XtSetArg(args[0], XmNgeometry, "558x174+330+496");
	XtSetValues(topLevelShell, args, 1);

	XtSetArg(args[0], XmNy, 0);
	XtSetArg(args[1], XmNx, 0);
	XtSetArg(args[2], XmNresizePolicy, XmRESIZE_NONE);
	XtSetArg(args[3], XmNheight, 60);
	XtSetArg(args[4], XmNwidth, 60);
	d = XtCreateManagedWidget("d", xmDrawingAreaWidgetClass, topLevelShell, args, 5);

	rc = new_text_object(d, 20, 10, 20, tst, &t);
	rc = new_text_object(d, 20, 50, 20, tst, &t1);

	XtRealizeWidget(topLevelShell);

	set_textstring(t, "XXXXXXXXXXX12345!");
	set_textstring(t1, "PPPHHT!");

	XtMainLoop();
}
