/**************************************************
* File: lxbApp.h - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* external variables */
extern Widget lxbApp;
extern Widget drawingArea_1;
extern Widget label_2;
extern Widget arrowButton_3;
extern Widget textF_4;
extern Widget rowColumn_6;
extern Widget pushButton_7;
extern Widget pushButton_8;
extern Widget pushButton_9;

