/**************************************************
* File: lxbApp.c - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* include files */
#include <stdio.h>

#include <Xm/Xm.h>
#include <Xm/ScrolledW.h>
#include <Xm/ScrollBar.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include <Xm/ArrowB.h>
#include <Xm/CascadeB.h>
#include <Xm/Separator.h>
#include <Xm/DrawnB.h>
#include <Xm/Scale.h>
#include <Xm/Frame.h>
#include <Xm/Form.h>
#include <Xm/RowColumn.h>
#include <Xm/Label.h>
#include <Xm/TextF.h>
#include <Xm/Text.h>
#include <Xm/List.h>
#include <Xm/DrawingA.h>
#include <Xm/MenuShell.h>
#include <X11/Shell.h>

#include "lxbApp_util.h"
#include "lxbApp.h"

/* global variables */
Widget lxbApp;
Widget drawingArea_1;
Widget label_2;
Widget arrowButton_3;
Widget textF_4;
Widget rowColumn_6;
Widget pushButton_7;
Widget pushButton_8;
Widget pushButton_9;

/* local prototypes */
static void
build_gui(Widget lxbApp);

/**************************************************
* Function: build_gui
**************************************************/
static void
build_gui(Widget lxbApp)
{
	Arg args[100];
	XmString xmstrings[10];
	XmFontList fontlist;

	XtSetArg(args[0], XmNy, 599);
	XtSetArg(args[1], XmNx, 2097);
	XtSetArg(args[2], XmNresizePolicy, XmRESIZE_NONE);
	XtSetArg(args[3], XmNheight, 60);
	XtSetArg(args[4], XmNwidth, 60);
	drawingArea_1 = XtCreateManagedWidget("drawingArea_1", xmDrawingAreaWidgetClass, lxbApp, args, 5);

	xmstrings[0] = XmStringCreateSimple("tst");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	XtSetArg(args[1], XmNbackground, get_pixel(lxbApp, "snow"));
	XtSetArg(args[2], XmNy, 34);
	XtSetArg(args[3], XmNx, 89);
	label_2 = XtCreateManagedWidget("label_2", xmLabelWidgetClass, drawingArea_1, args, 4);

	XmStringFree(xmstrings[0]);

	XtSetArg(args[0], XmNbackground, get_pixel(lxbApp, "red"));
	XtSetArg(args[1], XmNforeground, get_pixel(lxbApp, "green"));
	XtSetArg(args[2], XmNy, 290);
	XtSetArg(args[3], XmNx, 41);
	XtSetArg(args[4], XmNwidth, 60);
	XtSetArg(args[5], XmNheight, 60);
	arrowButton_3 = XtCreateManagedWidget("arrowButton_3", xmArrowButtonWidgetClass, drawingArea_1, args, 6);

	XtSetArg(args[0], XmNy, 112);
	XtSetArg(args[1], XmNx, 31);
	textF_4 = XtCreateManagedWidget("textF_4", xmTextFieldWidgetClass, drawingArea_1, args, 2);

	XtSetArg(args[0], XmNy, 163);
	XtSetArg(args[1], XmNx, 88);
	XtSetArg(args[2], XmNwidth, 60);
	XtSetArg(args[3], XmNheight, 30);
	rowColumn_6 = XtCreateManagedWidget("rowColumn_6", xmRowColumnWidgetClass, drawingArea_1, args, 4);

	pushButton_7 = XtCreateManagedWidget("pushButton_7", xmPushButtonWidgetClass, rowColumn_6, args, 0);

	pushButton_8 = XtCreateManagedWidget("pushButton_8", xmPushButtonWidgetClass, rowColumn_6, args, 0);

	pushButton_9 = XtCreateManagedWidget("pushButton_9", xmPushButtonWidgetClass, rowColumn_6, args, 0);

}
/**************************************************
* Function: main
**************************************************/
int 
main(int argc, char *argv[])
{
	Arg args[100];

	/* Initialize toolkit and parse command line options. */
	lxbApp = XtInitialize(NULL, "lxbApp", NULL, 0, &argc, argv);

	XtSetArg(args[0], XmNgeometry, "260x388+2097+599");
	XtSetValues(lxbApp, args, 1);

	build_gui(lxbApp);

	XtRealizeWidget(lxbApp);

	XtMainLoop();
}
