/**************************************************
* File: menubar_app.h - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

