/**************************************************
* File: menubar_app.c - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* include files */
#include <stdio.h>

#include <Xm/Xm.h>
#include <Xm/MainW.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/SeparatoG.h>
#include <Xm/PushB.h>
#include <Xm/PushBG.h>
#include <Xm/DrawingA.h>

#include "menubar_app_util.h"
#include "menu.h"

/* local prototypes */
static void
build_gui(Widget menubar_app);

/**************************************************
* Function: build_gui
**************************************************/
static void
build_gui(Widget menubar_app)
{
	Arg args[100];
	XmString xmstrings[10];

	Widget menubar1;
	Widget Files;
	Widget Edit;
	Widget Options;
	Widget pb0;
	Widget pushButton_12;
	Widget pushButton_13;
	Widget pushButton_14;
	Widget separator_15;
	Widget pushButton_16;
	Widget toggleButton_21;
	Widget toggleButton_22;
	Widget menushell_right, pb_right, pulldown_right, cb, ms;
	Widget pullright;
	Widget exit;

	Widget drawArea;
	Widget main_w, menubar, filepulldown;
	XmString label_str;

	/* create maine window */
	main_w = XtVaCreateManagedWidget ("main_w",
									   xmMainWindowWidgetClass, menubar_app,
									   XmNscrollingPolicy,      XmAUTOMATIC,
									   NULL);

	/* create the menubar */
	menubar = XmCreateMenuBar (main_w, "MenuBar", NULL, 0);

	/* create the "File" Menu */
	filepulldown = XmCreatePulldownMenu (menubar, "FilePullDown", NULL, 0);

	/* create the File button in the Menubar */
	label_str = XmStringCreateLocalized ("File");
	XtVaCreateManagedWidget ("File",
							xmCascadeButtonWidgetClass, menubar,
							XmNlabelString,  label_str,
							XmNmnemonic,    'F',
							XmNsubMenuId,    filepulldown,
							NULL);
	XmStringFree (label_str);

	/* Now add the menu items */
	XtVaCreateManagedWidget ("Open",
							xmPushButtonGadgetClass, filepulldown, NULL);
	XtVaCreateManagedWidget ("Save",
							xmPushButtonGadgetClass, filepulldown, NULL);

	/* create the pullright menu */
	pullright = XmCreatePulldownMenu(filepulldown, "Pullright", NULL, 0);
	XtVaCreateManagedWidget ("Pullright",
					xmCascadeButtonWidgetClass, filepulldown, 
					XmNsubMenuId, pullright,
					NULL);

	/* add the pullright menu items */
	XtVaCreateManagedWidget ("Pullright 1",
							xmPushButtonGadgetClass, pullright, NULL);
	XtVaCreateManagedWidget ("Pullright 2",
							xmPushButtonGadgetClass, pullright, NULL);

	XtVaCreateManagedWidget ("separator",
							xmSeparatorGadgetClass, filepulldown, NULL);

	exit = XtVaCreateManagedWidget ("Exit",
							xmPushButtonGadgetClass, filepulldown, NULL);

	XtManageChild (menubar);
}
/**************************************************
* Function: main
**************************************************/
int 
main(int argc, char *argv[])
{
	Arg args[100];
	Widget menubar_app;

	/* Initialize toolkit and parse command line options. */
	menubar_app = XtInitialize(NULL, "menubar_app", NULL, 0, &argc, argv);

	XtSetArg(args[0], XmNgeometry, "577x355+100+200");
	XtSetValues(menubar_app, args, 1);

	build_gui(menubar_app);

	XtRealizeWidget(menubar_app);

	XtMainLoop();
}
/*******************************************************
	drawArea = XtVaCreateManagedWidget ("drawArea",
									   xmDrawingAreaWidgetClass, main_w,
									   XmNwidth,  500,
									   XmNheight, 500,
									   NULL);

	menubar = XmVaCreateSimplePulldownMenu(drawArea, "menubar", NULL,
									XmVaPUSHBUTTON, "Line", 'L', NULL, NULL,
									XmVaPUSHBUTTON, "Square", 'S', NULL, NULL,
									XmVaPUSHBUTTON, "Circle", 'C', NULL, NULL,
									XmVaCASCADEBUTTON, "Wieght", 'W',
									XmVaSEPARATOR,
									XmVaPUSHBUTTON, "Exit", 'x', "Ctrl<Key>c", "Ctrl<c>",
									NULL);
*******************************************************/
