/**************************************************
* File: wtree.h - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* global variables */
extern Widget tree;

void
build_wtree_area(Widget tst);
