/**************************************************
* File: pallet_util.h - lxb utilities header file
*
*    This file is generated by the program lxb.
*
**************************************************/

Pixel
get_pixel(Widget w, char *resource_value);
XmFontList
get_fontlist(Widget w, char *fontname);
