/**************************************************
* File: pallet.c - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* include files */
#include <stdio.h>

#include <Xm/Xm.h>
#include <Xm/ScrolledW.h>
#include <Xm/ScrollBar.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include <Xm/ArrowB.h>
#include <Xm/CascadeB.h>
#include <Xm/Separator.h>
#include <Xm/DrawnB.h>
#include <Xm/Scale.h>
#include <Xm/Frame.h>
#include <Xm/Form.h>
#include <Xm/RowColumn.h>
#include <Xm/Label.h>
#include <Xm/TextF.h>
#include <Xm/Text.h>
#include <Xm/List.h>
#include <Xm/DrawingA.h>
#include <Xm/MenuShell.h>
#include <X11/Shell.h>

#include "pallet_util.h"
#include "pallet.h"

/* global variables */
Widget topLevelShell;
Widget drawingArea_1;
Widget arrowButton_2;
Widget separator_3;
Widget scale_4;
Widget textF_7;
Widget label_8;
Widget rowColumn_9;
Widget toggleButton_10;
Widget toggleButton_11;

/* local prototypes */
static void
build_gui(Widget topLevelShell);

/**************************************************
* Function: build_gui
**************************************************/
static void
build_gui(Widget topLevelShell)
{
	Arg args[100];
	XmString xmstrings[10];
	XmFontList fontlist;

	XtSetArg(args[0], XmNy, 534);
	XtSetArg(args[1], XmNx, 265);
	XtSetArg(args[2], XmNresizePolicy, XmRESIZE_NONE);
	XtSetArg(args[3], XmNheight, 60);
	XtSetArg(args[4], XmNwidth, 60);
	drawingArea_1 = XtCreateManagedWidget("drawingArea_1", xmDrawingAreaWidgetClass, topLevelShell, args, 5);

	XtSetArg(args[0], XmNforeground, get_pixel(topLevelShell, "green"));
	XtSetArg(args[1], XmNbackground, get_pixel(topLevelShell, "blue"));
	XtSetArg(args[2], XmNy, 298);
	XtSetArg(args[3], XmNx, 145);
	XtSetArg(args[4], XmNwidth, 110);
	XtSetArg(args[5], XmNheight, 99);
	arrowButton_2 = XtCreateManagedWidget("arrowButton_2", xmArrowButtonWidgetClass, drawingArea_1, args, 6);

	XtSetArg(args[0], XmNy, 260);
	XtSetArg(args[1], XmNx, 10);
	XtSetArg(args[2], XmNheight, 16);
	XtSetArg(args[3], XmNwidth, 415);
	separator_3 = XtCreateManagedWidget("separator_3", xmSeparatorWidgetClass, drawingArea_1, args, 4);

	XtSetArg(args[0], XmNy, 10);
	XtSetArg(args[1], XmNx, 398);
	XtSetArg(args[2], XmNwidth, 14);
	XtSetArg(args[3], XmNheight, 156);
	scale_4 = XtCreateManagedWidget("scale_4", xmScaleWidgetClass, drawingArea_1, args, 4);

	XtSetArg(args[0], XmNforeground, get_pixel(topLevelShell, "purple3"));
	XtSetArg(args[1], XmNbackground, get_pixel(topLevelShell, "PapayaWhip"));
	fontlist = get_fontlist(topLevelShell, "-adobe-helvetica-medium-o-normal--25-180-100-100-p-130-iso8859-1");
	XtSetArg(args[2], XmNfontList, fontlist);
	XtSetArg(args[3], XmNy, 203);
	XtSetArg(args[4], XmNx, 85);
	textF_7 = XtCreateManagedWidget("textF_7", xmTextFieldWidgetClass, drawingArea_1, args, 5);

	XmFontListFree(fontlist);

	fontlist = get_fontlist(topLevelShell, "-misc-fixed-bold-r-normal--13-100-100-100-c-80-iso8859-1");
	XtSetArg(args[0], XmNfontList, fontlist);
	xmstrings[0] = XmStringCreateSimple("Enter:");
	XtSetArg(args[1], XmNlabelString, xmstrings[0]);
	XtSetArg(args[2], XmNbackground, get_pixel(topLevelShell, "gray90"));
	XtSetArg(args[3], XmNy, 226);
	XtSetArg(args[4], XmNx, 18);
	label_8 = XtCreateManagedWidget("label_8", xmLabelWidgetClass, drawingArea_1, args, 5);

	XmStringFree(xmstrings[0]);

	XmFontListFree(fontlist);

	XtSetArg(args[0], XmNorientation, XmHORIZONTAL);
	XtSetArg(args[1], XmNy, 132);
	XtSetArg(args[2], XmNx, 20);
	XtSetArg(args[3], XmNwidth, 16);
	XtSetArg(args[4], XmNheight, 16);
	rowColumn_9 = XtCreateManagedWidget("rowColumn_9", xmRowColumnWidgetClass, drawingArea_1, args, 5);

	xmstrings[0] = XmStringCreateSimple("Push ME!");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	fontlist = get_fontlist(topLevelShell, "-misc-fixed-bold-r-normal--13-100-100-100-c-80-iso8859-1");
	XtSetArg(args[1], XmNfontList, fontlist);
	XtSetArg(args[2], XmNy, 3);
	XtSetArg(args[3], XmNx, 3);
	toggleButton_10 = XtCreateManagedWidget("toggleButton_10", xmToggleButtonWidgetClass, rowColumn_9, args, 4);

	XmStringFree(xmstrings[0]);

	XmFontListFree(fontlist);

	xmstrings[0] = XmStringCreateSimple("NO! Push ME!");
	XtSetArg(args[0], XmNlabelString, xmstrings[0]);
	fontlist = get_fontlist(topLevelShell, "-misc-fixed-bold-r-normal--13-100-100-100-c-80-iso8859-1");
	XtSetArg(args[1], XmNfontList, fontlist);
	XtSetArg(args[2], XmNy, 3);
	XtSetArg(args[3], XmNx, 151);
	toggleButton_11 = XtCreateManagedWidget("toggleButton_11", xmToggleButtonWidgetClass, rowColumn_9, args, 4);

	XmStringFree(xmstrings[0]);

	XmFontListFree(fontlist);

}
/**************************************************
* Function: main
**************************************************/
int 
main(int argc, char *argv[])
{
	Arg args[100];

	/* Initialize toolkit and parse command line options. */
	topLevelShell = XtInitialize(NULL, "pallet", NULL, 0, &argc, argv);

	XtSetArg(args[0], XmNgeometry, "440x411+270+561");
	XtSetValues(topLevelShell, args, 1);

	build_gui(topLevelShell);

	XtRealizeWidget(topLevelShell);

	XtMainLoop();
}
