/**************************************************
* File: pallet.h - application source file
*
*    This file is generated by the program lxb.
*
**************************************************/

/* external variables */
extern Widget topLevelShell;
extern Widget drawingArea_1;
extern Widget arrowButton_2;
extern Widget separator_3;
extern Widget scale_4;
extern Widget Title;
extern Widget Scrollbar;
extern Widget textF_7;
extern Widget label_8;
extern Widget rowColumn_9;
extern Widget toggleButton_10;
extern Widget toggleButton_11;

